/**
 * Mock processing service for frontend-only testing.
 * Simulates the real-time processing flow without backend/database dependencies.
 */

import type { SmeltProgressDTO, SmeltFileProgressDTO, SmeltResultDTO, SmeltStatus } from "@/types";
import type { FileWithValidation } from "@/store/types";

/**
 * Check if mock mode is enabled via environment variable.
 */
export function isMockModeEnabled(): boolean {
  return import.meta.env.PUBLIC_MOCK_PROCESSING === "true";
}

interface MockStage {
  status: SmeltStatus;
  percentage: number;
  message: string;
  duration: number;
}

const MOCK_STAGES: MockStage[] = [
  { status: "validating", percentage: 5, message: "VALIDATING FILES...", duration: 600 },
  { status: "validating", percentage: 10, message: "FILES VALIDATED", duration: 400 },
  { status: "decoding", percentage: 15, message: "DECODING AUDIO...", duration: 500 },
  { status: "decoding", percentage: 20, message: "AUDIO DECODED", duration: 500 },
  { status: "transcribing", percentage: 30, message: "TRANSCRIBING...", duration: 800 },
  { status: "transcribing", percentage: 45, message: "TRANSCRIBING...", duration: 1000 },
  { status: "transcribing", percentage: 60, message: "TRANSCRIBING...", duration: 1000 },
  { status: "transcribing", percentage: 70, message: "TRANSCRIPTION COMPLETE", duration: 700 },
  { status: "synthesizing", percentage: 80, message: "GENERATING OUTPUT...", duration: 600 },
  { status: "synthesizing", percentage: 90, message: "FINALIZING...", duration: 500 },
  { status: "synthesizing", percentage: 95, message: "ALMOST DONE...", duration: 400 },
];

const MOCK_MARKDOWN_CONTENT = `# Meeting Summary

## Key Points
- Discussed Q4 roadmap and priorities
- Agreed on new feature development timeline
- Reviewed budget allocation for next quarter

## Action Items
1. **John** - Prepare technical specification by Friday
2. **Sarah** - Schedule stakeholder meeting for next week
3. **Team** - Review and comment on draft proposal

## Decisions Made
- Approved moving forward with Phase 2 implementation
- Selected vendor A for infrastructure upgrade
- Postponed mobile app redesign to Q1

## Notes
The team expressed enthusiasm about the new direction. Several innovative ideas were proposed for improving user engagement. Follow-up meeting scheduled for December 15th.

---
*Generated by SMELT*`;

export interface MockProcessingCallbacks {
  onProgress: (progress: SmeltProgressDTO, fileProgress: SmeltFileProgressDTO[]) => void;
  onCompleted: (results: SmeltResultDTO[]) => void;
  onFailed: (code: string, message: string) => void;
}

/**
 * Convert a filename to markdown output filename.
 * audio.mp3 -> audio.md
 * text_input -> text_input.md
 */
function toMarkdownFilename(filename: string): string {
  const dotIndex = filename.lastIndexOf(".");
  if (dotIndex > 0) {
    return filename.slice(0, dotIndex) + ".md";
  }
  return filename + ".md";
}

/**
 * Run mock processing simulation.
 * Simulates the stages with realistic timing and generates mock results.
 */
export function runMockProcessing(files: FileWithValidation[], text: string, callbacks: MockProcessingCallbacks): void {
  const validFiles = files.filter((f) => f.isValid);
  const hasText = text.trim().length > 0;

  // Build file progress entries
  const fileProgressEntries: SmeltFileProgressDTO[] = validFiles.map((f, index) => ({
    id: `mock-file-${index}`,
    status: "pending" as const,
    progress: 0,
  }));

  // Add text input as a pseudo-file if present
  if (hasText) {
    fileProgressEntries.push({
      id: "mock-text-input",
      status: "pending" as const,
      progress: 0,
    });
  }

  let currentStageIndex = 0;

  function processNextStage(): void {
    if (currentStageIndex >= MOCK_STAGES.length) {
      // Processing complete - generate results
      const results: SmeltResultDTO[] = [];

      // Generate result for each file
      validFiles.forEach((f, index) => {
        results.push({
          file_id: `mock-file-${index}`,
          filename: toMarkdownFilename(f.file.name),
          content: MOCK_MARKDOWN_CONTENT,
        });
      });

      // Generate result for text input if present
      if (hasText) {
        results.push({
          file_id: "mock-text-input",
          filename: "text_input.md",
          content: MOCK_MARKDOWN_CONTENT,
        });
      }

      callbacks.onCompleted(results);
      return;
    }

    const stage = MOCK_STAGES[currentStageIndex];

    // Update file progress based on overall progress
    const updatedFileProgress: SmeltFileProgressDTO[] = fileProgressEntries.map((fp) => ({
      ...fp,
      status: stage.status as SmeltFileProgressDTO["status"],
      progress: stage.percentage,
    }));

    const progress: SmeltProgressDTO = {
      percentage: stage.percentage,
      stage: stage.status,
      message: stage.message,
    };

    callbacks.onProgress(progress, updatedFileProgress);

    currentStageIndex++;
    setTimeout(processNextStage, stage.duration);
  }

  // Start processing after a short initial delay
  setTimeout(processNextStage, 200);
}
